name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint (Standard)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run standardrb
        run: bundle exec standardrb

  mysql:
    name: Test (MySQL)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
        ruby:
          - 3.4
          - 3.3
          - 3.2
          - 3.1
          - "3.0"
        exclude:
          - gemfile: Gemfile
            ruby: 3.1
          - gemfile: Gemfile
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-0
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: 3.4

    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: "%"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_ADAPTER: mysql2
          DB_HOST: 127.0.0.1
        run: ./bin/test

  postgres:
    name: Test (Postgres)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
        ruby:
          - 3.4
          - 3.3
          - 3.2
          - 3.1
        exclude:
          - gemfile: Gemfile
            ruby: 3.1
          - gemfile: Gemfile
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-0
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: 3.4

    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_ADAPTER: postgresql
          DB_HOST: localhost
        run: ./bin/test

  sqlite:
    name: Test (SQLite3)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
        ruby:
          - 3.4
          - 3.3
          - 3.2
          - 3.1
        exclude:
          - gemfile: Gemfile
            ruby: 3.1
          - gemfile: Gemfile
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: "3.0"
          - gemfile: gemfiles/Gemfile-rails-7-0
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-1
            ruby: 3.4
          - gemfile: gemfiles/Gemfile-rails-6-0
            ruby: 3.4

    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: ./bin/test
